version: '3.8'

services:
  app:
    build: .
    container_name: epubar
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///data/epubar.db
    restart: unless-stopped
